#!/usr/bin/env bash
# Generate the device's embedded assets into src/assets_gen/:
#   - LVGL C-array fonts for the seven ThemeFonts roles (lv_font_conv via npx)
#   - the boot logo as an RGB565 lv_image_dsc_t (LVGLImage.py from the LVGL tree)
#   - config_seed.h: WiFi-only first-boot NVS seed, from panel_seed.json at the
#     repo root if present. Embeds REAL WiFi credentials and is gitignored --
#     never commit it. The MQTT broker, login, topic base and CA are NOT seeded:
#     they come from config/cooler_defaults.h (tools/import_cooler_broker.sh).
#
# Run from anywhere; paths resolve relative to this script. Requires: node
# (npx) unless FONTS=0, python3 with Pillow + pypng (for LVGLImage.py), and an
# initialized PlatformIO libdeps tree (for LVGLImage.py itself).
#
#   FONTS=0 device/tools/gen_assets.sh     # images + seed only, keep the fonts
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
DEV="$HERE/.."
REPO="$DEV/.."
TTF="$REPO/assets/ttf"
OUT="$DEV/src/assets_gen"
RANGE='0x20-0x7F,0xB0,0xB7,0x2014,0x2248'   # ASCII + ° · — ≈
PY="${PYTHON:-python3}"
LVGL_IMG="$DEV/.pio/libdeps/esp32s3-86box/lvgl/scripts/LVGLImage.py"

mkdir -p "$OUT"

font() { # name ttf size
    echo "font: $1 ($2 @ $3px)"
    npx --yes lv_font_conv --font "$TTF/$2" --size "$3" --bpp 4 --format lvgl \
        --range "$RANGE" --no-compress -o "$OUT/font_$1.c" --force-fast-kern-format
    # lv_font_conv emits '#include "lvgl/lvgl.h"' — our include path is <lvgl.h>
    sed -i 's|#include "lvgl/lvgl.h"|#include <lvgl.h>|' "$OUT/font_$1.c"
}

if [ "${FONTS:-1}" != "0" ]; then
font hero     Inter-SemiBold.ttf        30
font title    Inter-SemiBold.ttf        18
font body     Inter-Medium.ttf          13
font overline Inter-Medium.ttf          10
font num_sm   JetBrainsMono-Regular.ttf 11
font num_md   JetBrainsMono-Medium.ttf  13
font hero_lg  Inter-SemiBold.ttf        42
fi

echo "logo: prescale + RGB565 C array"
"$PY" - <<EOF
from PIL import Image
img = Image.open("$REPO/mockups/northtrail_logo.png").convert("RGB")
img = img.resize((298, 72), Image.LANCZOS)
img.save("$OUT/_logo_298x72.png")
wm = Image.open("$REPO/assets/brand/cooler32-wordmark-dark.png").convert("RGBA")
wm = wm.resize((round(wm.width * 64 / wm.height), 64), Image.LANCZOS)   # 64px tall
wm.save("$OUT/_wordmark.png")
EOF
"$PY" "$LVGL_IMG" --ofmt C --cf RGB565 -o "$OUT" "$OUT/_logo_298x72.png"
mv "$OUT/_logo_298x72.c" "$OUT/logo.c"
sed -i 's/_logo_298x72/northtrail_logo/g; s|#include "lvgl/lvgl.h"|#include <lvgl.h>|' "$OUT/logo.c"
# Wordmark keeps its alpha (renders straight on the dark boot background).
"$PY" "$LVGL_IMG" --ofmt C --cf RGB565A8 -o "$OUT" "$OUT/_wordmark.png"
mv "$OUT/_wordmark.c" "$OUT/logo_wordmark.c"
sed -i 's/_wordmark/cooler32_wordmark/g; s|#include "lvgl/lvgl.h"|#include <lvgl.h>|' "$OUT/logo_wordmark.c"
rm -f "$OUT/_logo_298x72.png" "$OUT/_wordmark.png"

echo "seed: WiFi-only first-boot config (gitignored, real credentials)"
if [ -f "$REPO/panel_seed.json" ]; then
"$PY" - "$REPO/panel_seed.json" "$OUT/config_seed.h" <<'PY'
import json, sys
d = json.load(open(sys.argv[1]))
js = json.dumps({"wifi": d.get("wifi", {})}, indent=2)   # never seed the broker
lines = "\n".join('    "' + l.replace('\\', '\\\\').replace('"', '\\"') + '\\n"' for l in js.splitlines())
open(sys.argv[2], "w").write("// AUTO-GENERATED by gen_assets.sh -- DO NOT COMMIT (real WiFi credentials).\n"
    "#pragma once\nstatic const char kConfigSeedJson[] =\n" + lines + "\n    ;\n")
PY
elif [ ! -f "$OUT/config_seed.h" ]; then
  printf '#pragma once\nstatic const char kConfigSeedJson[] = "{}";\n' > "$OUT/config_seed.h"
fi
echo "done -> $OUT"
