// Points the shared ThemeFonts roles at the embedded C-array fonts
// (src/assets_gen/, generated by tools/gen_assets.sh). Mirrors the sim's
// fonts_freetype.cpp role mapping.
#include "theme.h"

extern "C" {
extern const lv_font_t font_hero;
extern const lv_font_t font_title;
extern const lv_font_t font_body;
extern const lv_font_t font_overline;
extern const lv_font_t font_num_sm;
extern const lv_font_t font_num_md;
extern const lv_font_t font_hero_lg;
}

void device_fonts_init() {
    ThemeFonts f;
    f.hero     = &font_hero;      // Inter-SemiBold 30
    f.title    = &font_title;     // Inter-SemiBold 18
    f.body     = &font_body;      // Inter-Medium 13
    f.overline = &font_overline;  // Inter-Medium 10
    f.num_sm   = &font_num_sm;    // JetBrainsMono-Regular 11
    f.num_md   = &font_num_md;    // JetBrainsMono-Medium 13
    f.hero_lg  = &font_hero_lg;   // Inter-SemiBold 42 (boot wordmark)
    theme_set_fonts(f);
}
