#!/usr/bin/env python3
"""Turn the card icons in assets/icons/ into LVGL A8 image descriptors.

A8 -- alpha only, no colour -- is deliberate. LVGL blends an A8 image using
the widget's `image_recolor` style as the fill (lv_draw_sw_img.c: A8 sets
blend_dsc.color = draw_dsc->recolor), so one 22x22 icon can render cyan when
its unit is running and grey when it is not, which is exactly the "only the
live thing is coloured" rule the trend screen is built on. An RGB icon would
be stuck at whatever teal the source art happened to be.

The sources are dark glyphs on opaque white, so alpha is 255 - luminance:
white background falls away, the glyph stays, and the white fan blades inside
the aircon box punch back through as holes. Output lands in shared/assets/
because BOTH builds compile it -- CMake globs shared/*.cpp, PlatformIO's
build_src_filter pulls +<../../shared/>.

Usage: python3 tools/gen_icons.py
"""
import os
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "assets", "icons")
OUT = os.path.join(ROOT, "shared", "assets", "icons.cpp")

SIZE = 22            # rendered edge, px. Bounded by the card, not by taste:
                     # "Running" at montserrat_20 reaches x=103 of the 141px
                     # status card, so anything larger collides with the text.
ICONS = [            # (source file, C symbol)
    ("snowflake.png", "icon_snowflake"),
    ("duty.png",      "icon_duty"),
    ("aircon.png",    "icon_aircon"),
]


def to_alpha(path, size):
    """Crop to the glyph, fit it into a square, return `size`*`size` alpha bytes."""
    im = Image.open(path).convert("RGBA")
    # Flatten onto white first: a source with real transparency and one with a
    # painted white background then take the same path below.
    flat = Image.new("RGB", im.size, (255, 255, 255))
    flat.paste(im, mask=im.split()[3])
    lum = flat.convert("L")
    alpha = lum.point(lambda v: 255 - v)

    bbox = alpha.getbbox()          # tight box around anything non-white
    if bbox:
        alpha = alpha.crop(bbox)

    # Letterbox into a square so a wide glyph (the snowflake is 109x96) keeps
    # its proportions instead of being stretched to fill.
    w, h = alpha.size
    side = max(w, h)
    square = Image.new("L", (side, side), 0)
    square.paste(alpha, ((side - w) // 2, (side - h) // 2))
    small = square.resize((size, size), Image.LANCZOS)

    # Downscaling a detailed glyph to ~22px leaves its thin strokes at 30-50%
    # alpha, which on a dark card reads as a grey smudge rather than a line.
    # Lift the mid-tones (leaving true 0 and true 255 alone) so the aircon's
    # louvres and arrows survive; a straight contrast stretch would instead
    # eat the antialiasing that keeps the curves smooth.
    return small.point(lambda v: min(255, int(255.0 * (v / 255.0) ** 0.65 + 0.5)))


def emit(f, sym, img):
    data = img.tobytes()
    w, h = img.size
    f.write(f"\nstatic const LV_ATTRIBUTE_MEM_ALIGN uint8_t {sym}_map[] = {{\n")
    for i in range(0, len(data), 16):
        row = ",".join(f"0x{b:02x}" for b in data[i:i + 16])
        f.write(f"    {row},\n")
    f.write("};\n\n")
    f.write(f"extern const lv_image_dsc_t {sym} = {{\n")
    f.write("    .header = { .magic = LV_IMAGE_HEADER_MAGIC,\n")
    f.write("                .cf = LV_COLOR_FORMAT_A8, .flags = 0,\n")
    f.write(f"                .w = {w}, .h = {h}, .stride = {w}, .reserved_2 = 0 }},\n")
    f.write(f"    .data_size = sizeof({sym}_map),\n")
    f.write(f"    .data = {sym}_map,\n")
    f.write("    .reserved = NULL,\n")
    f.write("};\n")


def main():
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write("// GENERATED by tools/gen_icons.py from assets/icons/*.png -- do not edit.\n")
        f.write("// A8 (alpha-only) descriptors; tint with lv_obj_set_style_image_recolor().\n")
        f.write('#include "lvgl.h"\n#include <cstdint>\n\n')
        f.write("#ifndef LV_ATTRIBUTE_MEM_ALIGN\n#define LV_ATTRIBUTE_MEM_ALIGN\n#endif\n")
        for name, sym in ICONS:
            emit(f, sym, to_alpha(os.path.join(SRC, name), SIZE))
    print(f"wrote {OUT} ({os.path.getsize(OUT)} bytes, {len(ICONS)} icons @ {SIZE}px)")


if __name__ == "__main__":
    main()
