#!/usr/bin/env bash
# Generate config/cooler_defaults.h from the v4 cooler controller project, so the
# panel boots pointed at the right broker without anyone retyping credentials.
# Re-run whenever the broker, the panel login or the CA changes.
#
#   tools/import_cooler_broker.sh [controller-dir]      (default ../controller)
#
# Reads:
#   <controller>/secrets.yaml   mqtt_broker, panel_mqtt_username, panel_mqtt_password
#   <controller>/cooler-v4.yaml mqtt port, topic_prefix, certificate_authority
# Writes config/cooler_defaults.h -- git-ignored, it embeds the panel password.
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
CTRL="${1:-$HERE/../../controller}"
OUT="$HERE/../config/cooler_defaults.h"
[ -f "$CTRL/secrets.yaml" ] || { echo "not found: $CTRL/secrets.yaml" >&2; exit 1; }
[ -f "$CTRL/cooler-v4.yaml" ] || { echo "not found: $CTRL/cooler-v4.yaml" >&2; exit 1; }

python3 - "$CTRL" "$OUT" <<'EOF'
import re, sys
ctrl, out = sys.argv[1], sys.argv[2]
sec = open(f"{ctrl}/secrets.yaml").read()
yml = open(f"{ctrl}/cooler-v4.yaml").read()

def secret(k):
    m = re.search(rf'^{k}:\s*"?([^"\n]*)"?\s*$', sec, re.M)
    if not m or not m.group(1): sys.exit(f"secrets.yaml: missing {k}")
    return m.group(1)

# Scope the lookups to the top-level mqtt: block (port:/password: also appear
# under wifi:/ota:, and a whole-file search can silently pick the wrong one).
mqtt = re.search(r'^mqtt:\n((?:[ \t].*\n|\n)+)', yml, re.M)
if not mqtt: sys.exit("cooler-v4.yaml: no mqtt: block")
blk = mqtt.group(1)
port = re.search(r'^  port:\s*(\d+)', blk, re.M).group(1)
base = re.search(r'^  topic_prefix:\s*"?([^"\n]+)"?', blk, re.M).group(1)
ca = re.search(r'^  certificate_authority: \|-\n((?:    .*\n)+)', blk, re.M)
ca_pem = "".join(l[4:] + "\n" for l in ca.group(1).splitlines()) if ca else ""

def cstr(s): return '"' + s.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n') + '"'
ca_lines = "\n".join('    ' + cstr(l + "\n") for l in ca_pem.splitlines()) or '    ""'
open(out, "w").write(f"""// GENERATED by tools/import_cooler_broker.sh -- do not edit by hand, do not commit
// (embeds the panel's MQTT password). Source: {ctrl}
#pragma once
#define COOLER_DEFAULT_MQTT_HOST {cstr(secret('mqtt_broker'))}
#define COOLER_DEFAULT_MQTT_PORT {port}
#define COOLER_DEFAULT_MQTT_USER {cstr(secret('panel_mqtt_username'))}
#define COOLER_DEFAULT_MQTT_PASS {cstr(secret('panel_mqtt_password'))}
#define COOLER_DEFAULT_MQTT_BASE {cstr(base)}
// CA that signs the broker's certificate. Used whenever the port is 8883.
#define COOLER_DEFAULT_MQTT_CA \\
{ca_lines.replace(chr(10), ' ' + chr(92) + chr(10))}
// Bump when the defaults above move to a different broker. A panel whose saved
// settings are older gets its MQTT fields reset to these once (WiFi is kept).
#define COOLER_BROKER_VERSION 2
""")
print(f"wrote {out}: host={secret('mqtt_broker')} port={port} user={secret('panel_mqtt_username')} base={base} ca={'yes' if ca_pem else 'no'}")
EOF
